name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    uses: Truthdb/.github/.github/workflows/rust-ci.yml@issue-17-workflows
    with:
      install_packages: musl-tools
      rustup_targets: |
        x86_64-unknown-linux-musl
      cargo_test_command: cargo test --target x86_64-unknown-linux-musl
      cargo_build_command: cargo build --release --target x86_64-unknown-linux-musl
      artifact_name: truthdb-installer
      artifact_path: target/x86_64-unknown-linux-musl/release/truthdb-installer
